//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCaNhan.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyChiTieuCaNhan
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Amount { get; set; }
        public string Detail { get; set; }
    }
}
